/**
 *Submitted for verification at testnet.snowtrace.io on 2022-06-02
*/

// SPDX-License-Identifier: MIT
// compiler version must be greater than or equal to 0.8.10 and less than 0.9.0
pragma solidity ^0.8.10;

// generated by Github Copilot

contract HelloWorld {
    string public greet = "A merkle proof";
    string public greet2 = "Of nothing";
}